- package-lock.json
- package.json
- tsconfig.json
This fixes the a problem in the build output where code completion does not work because the typescript definition are in the src folder. This also excludes the story files from being included in the build output.
> Fix broken typescript definitions in build output

- package-lock.json
- package.json
- src/Checkbox/Checkbox.tsx
- src/Checkbox/__tests__/checkbox.test.jsx
- src/Checkbox/assets/check.svg
- src/Checkbox/assets/indeterminate.svg
- src/Checkbox/checkboxStyles.ts
- src/stories/Checkbox/Checkbox.stories.tsx
This PR is for adding the checkbox component and its documentation. The checked state is handled within the component itself, but could of course be overriden by forced rerenders with different props.
> Checkbox component

- package-lock.json
- package.json
- src/StackBanner/StackBanner.tsx
- src/StackBanner/StackBannerRow.tsx
- src/StackBanner/__tests__/stackBannerUtil.test.js
- src/StackBanner/stackBannerUtil.tsx
This PR is for updating and extending StackBanner styles. The error banner background color has been lightened easier readability. Props are now also spread to the StackBanner and StackBannerRow components for easier customization.
> StackBanner Styles Update

- src/Checkbox/Checkbox.tsx
- src/stories/Checkbox/Checkbox.stories.tsx
This PR is for removing the state from the checkbox component. Consuming apps will now need to manage the checked state after this change.
This PR closes issue #19.
> Removed state from the checkbox component.

- package-lock.json
- package.json
- src/StepFunctionGraph/Graph.tsx
This PR fixes an issue where on different monitors, especially external monitors, the center of the graph was calculated incorrectly based on the zoom's default value.
> Fix external monitor graph centering

- package-lock.json
- package.json
- src/RadioGroup/RadioGroup.tsx
- src/RadioGroup/__tests__/radioGroup.test.jsx
- src/RadioGroup/radioGroupStyles.ts
- src/stories/RadioGroup/RadioGroup.stories.tsx
This PR addresses and should close issue #51, adding the ability to make radio group labels and valid `ReactElement` and allowing the ability to disable individual options.
> Allow radio button content

- package-lock.json
- package.json
- src/StepFunctionGraph/Graph.tsx
- src/StepFunctionGraph/graphStyles.ts
- src/stories/StepFunctionGraph/StepFunctionGraph.stories.tsx
This PR adds a grab cursor to the step function graph when hovered over, increases the height of all storybook examples for step function graph by 200px, and adds a sentence explaining that the canvas can be panned.
> Enhance step function graph stories

- package-lock.json
- package.json
- src/Toggle/Toggle.tsx
- src/Toggle/__tests__/toggle.test.jsx
- src/Toggle/toggleStyles.ts
- src/index.ts
- src/stories/Toggle/Toggle.stories.tsx
This PR replaces the `string` type in the toggle component options with a generic type to allow for more flexible and robust usage. The toggle options `name` field was also renamed to `label`. `npm start` was added to the package.json scripts to run the storybook command. The toggle margin was made dynamic based on the position of the label.
> Toggle component generics

- package-lock.json
- package.json
- src/TextArea/TextArea.tsx
This PR allows the user to add a ref  prop to the TextArea component and closes #75 if approved.
> Add ref forwarding to TextArea

- package-lock.json
- package.json
- src/stories/tsconfig.json
Added a tsconfig in the stories folder so the files within can resolve modules correctly while staying out of the rollup build that uses the main tsconfig in the root directory.
> Fix stories folder tsconfig

- package-lock.json
- package.json
- src/Input/Input.tsx
This PR adds ref forwarding to the Input component. The purpose of this is for the current Input component to plug and play nicely with react-hook-form (https://react-hook-form.com/get-started).
> Add ref forwarding to Input component

- CONTRIBUTING.md
- package-lock.json
- package.json
- rollup.config.js
- src/Filter/Filter.tsx
- src/Filter/components/FilterSectionHeader/FilterSectionHeader.tsx
- src/Filter/components/FilterSectionHeader/filterSectionHeaderStyles.ts
- tsconfig.json
This PR fixes the rollup build to create proper typings for components. The previous plugin was not compatible with absolute imports. SVGs need to be imported relative though or they get treated as external files, so I changed some paths.
> Fix TS build

- package-lock.json
- package.json
- src/Toggle/Toggle.tsx
- src/index.ts
- src/stories/Toggle/Toggle.stories.tsx
This PR addresses an issue that occurred due to SelectOption being imported and exported aliased as ToggleOption. If approved, this will close #123 .
> SelectOption aliased as ToggleOption build errors

- package-lock.json
- package.json
- src/Filter/modules/AdditionalJSONFilter/AdditionalJSONFilter.tsx
- src/Filter/modules/AdditionalJSONFilter/__tests__/additionalJSONFilter.test.js
- src/Filter/modules/ListFilter/ListFilter.tsx
- src/Filter/modules/ListFilter/__tests__/listFilter.test.js
- src/Filter/modules/MultiSelectFilter/MultiSelectFilter.tsx
- src/Filter/modules/MultiSelectFilter/__tests__/multiSelectFilter.test.js
- src/Filter/modules/RadioFilter/RadioFilter.tsx
- src/Filter/modules/RadioFilter/__tests__/radioFilter.test.js
- src/Filter/modules/SingleSelectFilter/SelectOverlay.tsx
- src/Filter/modules/SingleSelectFilter/SingleSelectFilter.tsx
- src/Filter/modules/SingleSelectFilter/__tests__/singleSelectFilter.test.js
- src/Filter/types/index.ts
- src/RadioGroup/RadioGroup.tsx
This PR allows numbers to be a valid input and return type when using the SingleSelect and Radio Filter modules. This also allows the FilterModule.getBrowserQueryUrlValue to return any type since parsing the value can truly return any value depending on how the user wants to implement the function.
> Single select typing error

- package-lock.json
- package.json
- src/Filter/modules/AdditionalJSONFilter/AdditionalJSONFilter.tsx
- src/Filter/modules/AdditionalJSONFilter/__tests__/additionalJSONFilter.test.js
- src/Filter/modules/ListFilter/ListFilter.tsx
- src/Filter/modules/ListFilter/__tests__/listFilter.test.js
- src/Filter/modules/MultiSelectFilter/MultiSelectFilter.tsx
- src/Filter/modules/MultiSelectFilter/__tests__/multiSelectFilter.test.js
- src/Filter/modules/RadioFilter/RadioFilter.tsx
- src/Filter/modules/RadioFilter/__tests__/radioFilter.test.js
- src/Filter/modules/SingleSelectFilter/SingleSelectFilter.tsx
- src/Filter/modules/SingleSelectFilter/__tests__/singleSelectFilter.test.js
- src/Filter/types/index.ts
- src/Filter/util/filterHooksUtil.tsx
This PR addresses an issue where the values output by the `getBrowserQueryUrlValue` method of some filter modules was now incorrect. If approved, this will close #142.
> Fix list filter

- package-lock.json
- package.json
- src/StepFunctionGraph/GraphRenderer.ts
- src/StepFunctionGraph/GraphUtil.ts
- src/StepFunctionGraph/__tests__/graphRenderer.test.ts
- src/StepFunctionGraph/__tests__/graphUtil.test.ts
- src/StepFunctionGraph/__tests__/utils/JSONBuilder.util.ts
- src/StepFunctionGraph/__tests__/utils/graphTestUtils.util.ts
This PR adds tests and bug fixes for the graphRenderer, mainly focusing on getX and renderVertex. There is still much room for more coverage, but this PR was starting to get long so I stopped here for now.
Some bugs that were fixed:
- Removed excessive space between nodes within a Parallel box
- Nodes that can overlap (specifically a node after a Map since they are wider) now more intelligently position further away
- Maps drawn in the top-left of a Parallel won't default to the center of the screen now
- Parallel nodes that aren't part of a choice now render by parent correctly
- Nested Map and Parallel nodes now have correct Y depth values (the adjusting function was not recursive so only the top level of anything was moved up)
> Increase step function test coverage - Part 2

- package-lock.json
- package.json
- src/Modal/Modal.tsx
This PR will close #155. The scroll is hidden for the main content whenever the modal is active.
When modals do not have scrollable (inner) content, the entire page behind the modal will scroll if the user uses the scroll wheel either hovering over the modal or the page itself. Scrolling should be blocked.
> Modal Scroll Issue Fix #155

- package-lock.json
- package.json
- src/Filter/modules/TextFilter/TextFilter.tsx
- src/Filter/modules/TextFilter/TextSearch.tsx
- src/Filter/modules/TextFilter/__tests__/textFilter.test.js
- src/Filter/modules/TextFilter/__tests__/textSearch.test.js
- src/Filter/types/index.ts
- src/stories/Filter/TextFilter/TextFilter.stories.tsx
- src/stories/Filter/TextFilter/TextFilterDocs.tsx
This PR is for adding support to limit text filter input to numbers only. If approved it will close #172.
**Note: `TextFilterOptions` was renamed `TextFilterOverrides` to mimic `ListFilterOverrides` in the `ListFilter` module. With that said, the argument order was left unchanged to avoid breaking current usage of the module.
> Textfilter number only support

- .github/workflows/storybook.yml
- package-lock.json
- package.json
- src/Filter/modules/DurationFilter/DurationFilter.tsx
This PR updates the Deploy GH Pages workflow to use npm ci instead of npm i to fix the workflow issue.
> Update Deploy GH Pages Workflow

- package-lock.json
- package.json
- src/CopyButton/CopyButton.tsx
- src/CopyButton/__tests__/CopyButton.test.js
- src/stories/MaskableImage/MaskableImage.stories.tsx
This PR will fix the maskable image link which is not working right now.
> Maskable image bug fix

- package-lock.json
- package.json
- src/Table/Table.tsx
- src/Table/__tests__/Table.test.jsx
- src/Table/assets/unsorted.svg
- src/Table/tableStyles.ts
- src/stories/Table/Table.stories.tsx
Description:
Updated [Lakefront table](https://toyotaresearchinstitute.github.io/lakefront/?path=%2Fdocs%2Flakefront-table--table) to support:
The table allows sorting by multiple columns (ascending and descending).
The table accepts a parameter setting the default sort.
Users can apply multiple sort criteria by shift-clicking on the columns.
A tooltip on the title indicates that multiple sort criteria are possible by shift-clicking to add to the sort.
Accepts width as a parameter.
> Table sortable by multiple columns

- package-lock.json
- package.json
- src/Table/Table.tsx
- src/Table/__tests__/Table.test.jsx
- src/Table/__tests__/tableUtil.test.tsx
- src/Table/tableUtil.tsx
- src/stories/Table/Table.stories.tsx
This PR is for updating the Table component specifically the initialSortBy. This will support an array of initialSortBy "ids" and if they are "desc" or not. This is for sorting columns in a table based on their initial desired sorting of multiple columns. Also still accepts one column value if desired. Added test and updated syntax that was missing.
> Add-easier-multi-sort-to-table

- package-lock.json
- package.json
- src/Filter/Filter.tsx
- src/Filter/types/index.ts
- src/Filter/util/filterHooksUtil.tsx
- src/Filter/util/filterUtil.ts
If approved, this will close https://github.com/ToyotaResearchInstitute/lakefront/issues/269.
In the file src/Filter/types/index.ts, remove the type (string | null)[]) from the function parseInitialFilterValue(browserQueryUrlValue?: string | string[] | null | undefined): T | null | undefined;
In the file src/Filter/util/filterHooksUtil.tsx, **location.search** should be cast as **UrlParameters**.
In the file src/Filter/util/filterUtil.ts, functions **getDefaultJsonViewValue**, **getDefaultValue** should take in an argument of type UrlParameters.
In the file src/Filter/Filter.tsx, location.search should be cast as **UrlParameters**.
> Cast url query param value(s) as UrlParameters and remove the type (string \ null)[]

- package-lock.json
- package.json
- src/components/Snackbar/index.ts
This is a quick PR to fix the way the snackbar message types enum is exported. The way it was changed the export from an enum to a value which caused issue in consuming applications.
> Snackbar message types export fix

- package-lock.json
- package.json
- src/components/Filter/modules/ListFilter/ListFilter.tsx
- src/components/Filter/modules/ListFilter/__tests__/listFilter.test.js
- src/components/Filter/util/__tests__/filterUtil.test.js
- src/components/Filter/util/filterUtil.ts
- src/stories/Filter/ListFilter/ListFilter.stories.tsx
Closing this PR will resolve issue #294 
When all selectable options are selected with an initial value provided, the url will display the entire url params. 
Resetting filters upon initial value provided, will reset all filters applied except the default initial filter. 
Previous functionality is still valid if no initial value is passed by default.
> ListFilter default all options fix

- package-lock.json
- package.json
- src/components/Button/Button.tsx
- src/components/Button/__tests__/button.test.jsx
- src/components/Button/buttonStyles.ts
- src/components/Button/buttonUtil.tsx
- src/components/RefreshToolbar/__tests__/__snapshots__/RefreshToolbar.test.jsx.snap
- src/stories/Button/Button.stories.tsx
Added additional prop "iconLabel". This will add a label under the icon button when icon prop is true.
This PR will close issue #271
> Add-labels-icon-button

- package-lock.json
- package.json
- src/lib/hooks/usePopover/PopoverContent/PopoverContent.tsx
This PR is a quick fix for the url in the popover content docs.
> Fixed broken link.

- .github/workflows/versionBumpCheck.yml
- package-lock.json
- package.json
- src/components/Breadcrumb/Breadcrumb.tsx
- src/components/Breadcrumb/BreadcrumbHeader.tsx
Added Link prop to Breadcrumbs to connect to application router.
> Add link prop for breadcrumbs

- package-lock.json
- package.json
- src/components/Breadcrumb/Breadcrumb.tsx
- src/components/Breadcrumb/__tests__/Breadcrumb.tests.jsx
- src/components/Breadcrumb/__tests__/BreadcrumbHeader.tests.jsx
- src/components/Breadcrumb/breadcrumbStyles.ts
This PR creates a dark mode version of Breadcrumb. Screenshots below:
> Breadcrumb dark mode

- package-lock.json
- package.json
- src/components/Table/Table.tsx
- src/components/Table/index.ts
- src/styles/theme.ts
- src/types/global.ts
This is a small PR to enhance the table component data type (making it generic) and removes the wrapping `ThemeProvider` to allow for external theme provider overrides.
> Table component theme and type updates

- package-lock.json
- package.json
- src/components/Select/Select.tsx
- src/components/Select/SelectOverlay.tsx
- src/stories/Select/Select.stories.tsx
This PR adds the ability to set default values on a `Select` component when using `isMulti` mode.
> Fix multi select initial value
