- .github/workflows/storybook.yml
- .gitignore
- README.md
- babel.config.js
- package-lock.json
- package.json
- src/Button/Button.tsx
- src/Button/__tests__/button.test.jsx
Some other changes:
- Add the license in package.json
- Update the readme with the storybook link for the button component
> Deploy storybook build to gh-pages

- package-lock.json
- package.json
This PR bumps the version to 0.5.0 to prepare a new release.
> Bumped version to 0.5.0.

- README.md
- package-lock.json
- package.json
- src/StackBanner/StackBanner.tsx
- src/StackBanner/StackBannerRow.tsx
- src/StackBanner/__tests__/stackBanner.test.jsx
- src/StackBanner/__tests__/stackBannerUtil.test.js
- src/StackBanner/__tests__/stackbannerRow.test.jsx
- src/StackBanner/assets/flag.svg
- src/StackBanner/stackBannerStyles.ts
- src/StackBanner/stackBannerUtil.tsx
- src/index.ts
- src/stories/StackBanner/StackBanner.stories.tsx
- src/stories/StackBanner/StackBannerRow.stories.tsx
This PR is for adding the Stack Banner component.
> Stack banner component

- package-lock.json
- package.json
- src/Input/inputStyles.ts
Added some styles for input height to make it the correct height.
> Adjust input height

- package-lock.json
- package.json
- src/index.ts
This PR is for exporting the Checkbox component so it is accessible to consumers.
> Added checkbox to index.

- package-lock.json
- package.json
- src/Input/Input.tsx
- src/Input/__tests__/input.test.jsx
- src/Input/inputStyles.ts
- src/stories/Input/Input.stories.tsx
> added error message and styling functionality to input component

- package-lock.json
- package.json
- src/Checkbox/Checkbox.tsx
This PR is for allowing the checkbox label to be any valid ReactElement.
> Added ReactElement as a label type option.

- README.md
- package-lock.json
- package.json
- src/SelectPopover/selectPopoverStyles.ts
Alphabetized the storybook links in the README, added some styles to the select popover to make sure they don't accidentally get overwritten by page styling.
> Select Popover style adjustments, README work.

- package-lock.json
- package.json
- src/Collapsible/Collapsible.tsx
Fixed typing to ensure our title prop typing overrides intrinsic div props.
> Collapsible Typing Updated

- CONTRIBUTING.md
- package-lock.json
- package.json
This PR addresses issue #38.
- Fixed link to readme => components.
- Fixed the component url template.
> Contributing documentation fix

- package-lock.json
- package.json
- src/SelectPopover/SelectPopover.tsx
- src/SelectPopover/__tests__/selectPopover.test.jsx
- src/SelectPopover/selectPopoverStyles.ts
- src/stories/SelectPopover/SelectPopover.stories.tsx
This PR is for adding the option to disable select popover items as needed. This addresses and will close #44 once approved.
> Add select popover disable functionality

- package-lock.json
- package.json
- src/StepFunctionGraph/__tests__/Digraph.test.ts
- src/StepFunctionGraph/__tests__/DigraphDFS.test.ts
This PR adds in some Digraph unit tests that didn't make the original Step Function Graph PR.
> Added Digraph and DigraphDFS tests.

- package-lock.json
- package.json
- src/RadioGroup/RadioGroup.tsx
- src/RadioGroup/__tests__/radioGroup.test.jsx
> Radio group unit tests

- package-lock.json
- package.json
- src/Collapsible/Collapsible.tsx
- src/Collapsible/__tests__/collapsible.test.jsx
- src/stories/Collapsible/Collapsible.stories.tsx
> Added ability to Collapsible component to hide expand/collapse button.

- package-lock.json
- package.json
- src/Toggle/Toggle.tsx
- src/index.ts
This PR adds the className prop to the new toggle component.
> Add className to toggle

- package-lock.json
- package.json
- src/Toggle/toggleStyles.ts
- src/styles/cloudColors.ts
This PR added blue colors and replaced toggle greens with blues.
> Replace Toggle component green colors

- README.md
- package-lock.json
- package.json
- src/Input/inputStyles.ts
- src/TextArea/TextArea.tsx
- src/TextArea/__tests__/textArea.test.jsx
- src/TextArea/textAreaStyles.ts
- src/index.ts
- src/stories/Input/Input.stories.tsx
- src/stories/TextArea/TextArea.stories.tsx
- src/styles/GlobalStyles.tsx
This PR is to create a TextArea component and if approve closes #70
> TextArea component

- package-lock.json
- package.json
- src/Loading/loadingStyles.ts
> Update emotion dependency in Loading component

- package-lock.json
- package.json
- src/stories/Filter/FilterPage/FilterPage.tsx
This PR is for fixing a render issue on first load of the Filter component. If approved, this will close #87 .
> Context menu fix

- package-lock.json
- package.json
- src/Filter/modules/SingleSelectFilter/__tests__/select.test.js
This PR fixes the broken single select filter test. If approved, this will close #102 .
> fix: Corrected broken single select filter test.

- README.md
- package-lock.json
- package.json
This PR adds the AdditionalJSONFilter link to the README file.
> Add AdditionalJSONFilter Link

- package-lock.json
- package.json
- src/Loading/loadingStyles.ts
This PR is for correcting issue #130 regarding the loading spinner color. If approved, this will close #130 .
> Fix for loading spinner color.

- package-lock.json
- package.json
- src/Modal/ConfirmationModal/ConfirmationModal.tsx
- src/Modal/ConfirmationModal/confirmationModalStyles.ts
This PR adds small fixes to the `ConfirmationModal` component. If approved, this will close #136 .
> Confirmation modal fixes

- README.md
- package-lock.json
- package.json
- src/CheckboxGroup/CheckboxGroup.tsx
- src/CheckboxGroup/__tests__/CheckboxGroup.test.jsx
- src/index.ts
- src/stories/CheckboxGroup/CheckboxGroup.stories.tsx
This PR creates a `CheckBoxGroup` in Lakefront. If approved, it will close #160.
1. Creates a CheckBox Group Component
2. Show the options with 'All'.
3. All the options are selected on load.
4. Uncheck the box will update the value selected and display the updated value on the top.
> Checkbox Group #160

- README.md
- package-lock.json
- package.json
- src/Table/Table.tsx
- src/Table/__tests__/Table.test.jsx
- src/Table/assets/arrow_drop_down.svg
- src/Table/assets/arrow_drop_up.svg
- src/Table/index.ts
- src/Table/tableStyles.ts
- src/index.ts
- src/stories/Table/Table.stories.tsx
- src/styles/lakefrontColors.ts
This PR includes a new Table Component for better maintenance and documentation. The story for the Table Component contains a button to clear and load the data. The appropriate message is displayed when the sorting on the table is changed.If approved, this will close #204 .
> Table component

- package-lock.json
- package.json
- src/Table/Table.tsx
This PR includes a small fix to add theme provider for table component to fix some style issues.
> Added ThemeProvider for Table Component.

- README.md
- package-lock.json
- package.json
- src/Breadcrumb/Breadcrumb.tsx
- src/Breadcrumb/BreadcrumbHeader.tsx
- src/Breadcrumb/__tests__/Breadcrumb.tests.jsx
- src/Breadcrumb/__tests__/BreadcrumbHeader.tests.jsx
- src/Breadcrumb/breadcrumbStyles.ts
- src/Breadcrumb/index.ts
- src/index.ts
- src/stories/Breadcrumb/Breadcrumb.stories.tsx
This PR includes a new Breadcrumb core component (including BreadcrumbHeader component in components/) moved into Lakefront and then replace usage in Lakehouse for easier maintenance and better documentation.If approved, this will close #208
> Bread crumb component

- README.md
- package-lock.json
- package.json
- src/Filter/modules/DurationFilter/DurationFilter.tsx
- src/Filter/modules/DurationFilter/MinMaxInput.tsx
- src/Filter/modules/DurationFilter/__tests__/DurationFilter.tests.js
- src/Filter/modules/DurationFilter/__tests__/MinMaxFilter.tests.jsx
- src/Filter/modules/DurationFilter/index.ts
- src/Filter/modules/index.ts
- src/Filter/util/__tests__/durationFilterUtil.test.js
- src/Filter/util/durationFilterUtil.ts
- src/stories/Filter/DurationFilter/DurationFilter.stories.tsx
- src/stories/Filter/DurationFilter/DurationFilterDocs.tsx
- src/stories/Filter/components/FilterPage/filterPageUtil.tsx
This PR includes a new Duration Filter Component for better documentation and maintenance. If approved, this will close #209.
> Duration Filter component

- package-lock.json
- package.json
- src/index.ts
This PR will trigger the Deploy GH Pages issue and run all the associated workflows.
> Fix Deploy GH Pages Issue

- .github/workflows/storybook.yml
- package-lock.json
- package.json
This PR sets the node version before running the npm install and npm run build-storybook to use npm 14 version.
> Issue Fix: Deploy GH Pages workflow fix

- .github/workflows/storybook.yml
- package-lock.json
- package.json
This PR adds the trigger for Deploy GH Pages workflow.
> Updated the trigger for Deploy GH Pages Workflow

- package-lock.json
- package.json
This PR updates the React to latest stable version "17.0.2".
> React version update

- README.md
- package-lock.json
- package.json
- src/CopyButton/CopyButton.tsx
- src/CopyButton/__tests__/CopyButton.test.js
This PR creates an IconOnly prop to set the IconOnly property. If set to true, it will display icon only. If approved this will close #158.
> Copy button update

- package-lock.json
- package.json
- src/ModeSelector/ModeSelector.tsx
- src/ModeSelector/__tests__/modeSelector.test.tsx
- src/ModeSelector/modeSelectorStyles.ts
- src/stories/ModeSelector/ModeSelector.stories.tsx
This PR is for adding a `ModeSelector` component. If approved, it will close #249 .
> Mode selector component

- .github/pull_request_template.md
- package-lock.json
- package.json
In order to better prevent creating new components without performing all of the contribution steps, created a pull request checklist which will be rendered for every PR.
> Created pull request template.

- package-lock.json
- package.json
- rollup.config.js
This PR was opened to address unnecessary comments appearing in the bundled application.  If approved, this will close #248 .
> Minified Application Bundle

- package-lock.json
- package.json
- src/Snackbar/snackbarStyles.ts
This PR is to address styling that was not aligning correctly when implemented. This is only a style update itself.
> Snackbar style update fix

- package-lock.json
- package.json
- src/Snackbar/index.tsx
This PR is a hotfix to add the `className` prop to the Snackbar component.
> Snackbar style class bug fix

- package-lock.json
- package.json
- src/Filter/modules/MultiSelectFilter/MultiSelectFilter.tsx
This PR is for setting the node engine to `16.x`, which will now match what is used in each of the [github workflows/actions](https://github.com/ToyotaResearchInstitute/lakefront/tree/main/.github/workflows) and ensure security patches are applied. If approved, this will close #285 .
> patch: Updated node engine specification to 16.x

- .github/workflows/branch.yml
- .github/workflows/main.yml
- .github/workflows/prerelease.yml
- .github/workflows/pullRequestCheck.yml
- .github/workflows/release.yml
- .github/workflows/storybook.yml
- .github/workflows/versionBumpCheck.yml
- package-lock.json
- package.json
This PR is for updating the workflows to reflect the latest version of node 18.
> Workflow versioning update

- package-lock.json
- package.json
- src/components/Select/Select.tsx
This PR is for adding optional props to Select.tsx.
> add-props-for-select-component

- package-lock.json
- package.json
- src/components/Select/Select.tsx
- src/components/Select/SelectOverlay.tsx
- src/components/Select/__tests__/Select.tests.jsx
- src/stories/Select/Select.stories.tsx
This PR edits the existing Select component to allow for selecting multiple values in a dropdown.
> Fix multi select

- package-lock.json
- package.json
- src/components/Button/Button.tsx
- src/components/Button/__tests__/button.test.jsx
- src/components/Button/buttonStyles.ts
-added disabled styling to icon label when button has disabled attribute
> Change disable icon label

- .github/pull_request_template.md
- .github/workflows/branch.yml
- .github/workflows/main.yml
- .github/workflows/prerelease.yml
- .github/workflows/pullRequestCheck.yml
- .github/workflows/release.yml
- .github/workflows/storybook.yml
- .github/workflows/versionBumpCheck.yml
- CONTRIBUTING.md
- README.md
- main.mustache
- package-lock.json
- package.json
- src/components/CopyButton/CopyButton.tsx
- src/lib/hooks/usePopover/PopoverContent/PopoverContent.tsx
> Woven planet

- .github/workflows/branch.yml
- .github/workflows/main.yml
- .github/workflows/prerelease.yml
- .github/workflows/pullRequestCheck.yml
- .github/workflows/release.yml
- .github/workflows/storybook.yml
- .github/workflows/versionBumpCheck.yml
- package-lock.json
- package.json
- [X ]  Ensure version numbers were bumped properly.
> Update node to 20

- README.md
- package-lock.json
- package.json
> Updated the usage language in the README.md
